#!/usr/bin/env bash
# Parse Apache log files in list format.
# Group visitors by their IP and HTTP status code.
# Displaying the number of occurances, IP, And HTTP status
# code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
